aspNetCoreDersCalisma/ViewComponents/StudentListViewComponent.cs
using aspNetCoreDersCalisma.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System.Linq;

namespace aspNetCoreDersCalisma.ViewComponents
{
    public class StudentListViewComponent :ViewComponent
    {
        private SchoolContext _context;

        public StudentListViewComponent(SchoolContext context)
        {
            _context = context;
        }

        public ViewViewComponentResult Invoke(string filter)
        {
            filter = HttpContext.Request.Query["filter"];
            return View(new StudentListViewModel
            {
                Students = _context.Students.Where(s => s.FirstName.ToLower().Contains(filter)).ToList()
            });
        }
    }
}

aspNetCoreDersCalisma/Views/Shared/DivideByZeroException.cshtml
@{
    Exception exception = ViewData["HandleException"] as Exception;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <h1>Divide by zero exception </h1>
</body>
</html>

aspNetCoreDersCalisma/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>Menu</div>
    <div>
        @await Component.InvokeAsync("StudentList",new{filter="a"})  
        @RenderBody()
    </div>
    <div>Footer</div>
    <div>
        @RenderSection("MySection",false)
    </div>
</body>
</html>